// GENERATED by AI agent (JS-safe) - ESM version
export default function mountDiag(app) {
  app.get('/api/_diag/routes', function(_req, res) {
    var router = app && app._router ? app._router : null;
    var stack = router && Array.isArray(router.stack) ? router.stack : [];
    var paths = [];
    for (var i = 0; i < stack.length; i++) {
      var r = stack[i];
      if (r && r.route && r.route.path) paths.push(r.route.path);
    }
    res.json({ count: paths.length, paths: paths });
  });
  
  app.get('/api/_diag/env', function(_req, res) {
    function mark(k){ return process.env[k] ? 'SET' : 'UNSET'; }
    res.json({
      STORAGE_BASE_PREFIX: process.env.STORAGE_BASE_PREFIX || '(empty)',
      AZURE_STORAGE_CONNECTION_STRING: mark('AZURE_STORAGE_CONNECTION_STRING'),
      AZURE_STORAGE_CONTAINER_NAME: process.env.AZURE_STORAGE_CONTAINER_NAME || '(empty)',
      FRONTEND_URL: process.env.FRONTEND_URL || '(empty)',
      NODE_ENV: process.env.NODE_ENV || '(empty)'
    });
  });
  
  app.get('/api/version', function(_req, res) {
    res.json({
      version: process.env.GIT_SHA || process.env.VERCEL_GIT_COMMIT_SHA || '(unknown)',
      builtAt: process.env.BUILT_AT || new Date().toISOString()
    });
  });
}
