// GENERATED by AI agent on 2025-09-26
import type { Express } from 'express';

export default function mountDiag(app: Express) {
  app.get('/api/_diag/routes', (_req, res) => {
    const paths = (app as any)?._router?.stack?.flatMap((r: any) =>
      r?.route?.path ? [r.route.path] : []
    ) || [];
    res.json({ count: paths.length, paths });
  });

  app.get('/api/_diag/env', (_req, res) => {
    const mark = (k: string) => process.env[k] ? 'SET' : 'UNSET';
    res.json({
      STORAGE_BASE_PREFIX: process.env.STORAGE_BASE_PREFIX || '(empty)',
      AZURE_STORAGE_CONNECTION_STRING: mark('AZURE_STORAGE_CONNECTION_STRING'),
      AZURE_STORAGE_CONTAINER_NAME: process.env.AZURE_STORAGE_CONTAINER_NAME || '(empty)',
      FRONTEND_URL: process.env.FRONTEND_URL || '(empty)',
      NODE_ENV: process.env.NODE_ENV || '(empty)'
    });
  });

  app.get('/api/version', (_req, res) => {
    res.json({
      version: process.env.GIT_SHA || process.env.VERCEL_GIT_COMMIT_SHA || '(unknown)',
      builtAt: process.env.BUILT_AT || new Date().toISOString()
    });
  });
}
