// GENERATED by AI agent (JS-safe) - CJS version
const mountDiag = require('./_diag.cjs');
const authDefault = require('./auth.cjs');

function registerRoutes(app) {
  // API routes - only JS files for now
  app.use('/api/auth', authDefault);
  
  // 診断用エンドポイント
  mountDiag(app);
  
  console.log('[BOOT] routes mounted');
}

module.exports = registerRoutes;
