// GENERATED by AI agent (JS-safe) - ESM version
import mountDiag from './_diag.js';
import authDefault from './auth.js';

export default function registerRoutes(app) {
  // API routes - only JS files for now
  app.use('/api/auth', authDefault);
  
  // 診断用エンドポイント
  mountDiag(app);
  
  console.log('[BOOT] routes mounted');
}
