// GENERATED by AI agent on 2025-09-27
// Minimal server for debugging SIGINT issue

import express from 'express';

const app = express();
const PORT = 8001;

// Basic middleware
app.use(express.json());

// Basic health endpoint
app.get('/api/health', (req, res) => {
  res.json({ ok: true, status: 'healthy' });
});

// Start server
app.listen(PORT, '0.0.0.0', () => {
  console.log(`🚀 Minimal server running on 0.0.0.0:${PORT}`);
  console.log(`📊 Health endpoint: http://0.0.0.0:${PORT}/api/health`);
  console.log('⏰ Server started successfully');
});

// SIGINT handler
process.on('SIGINT', () => {
  console.log('SIGINT received in minimal server, shutting down gracefully');
  process.exit(0);
});

console.log('Minimal server script loaded');
