export declare const users: any;
export declare const chats: any;
export declare const messages: any;
export declare const media: any;
export declare const emergencyFlows: any;
export declare const images: any;
export declare const documents: any;
export declare const keywords: any;
export declare const chatExports: any;
export declare const insertUserSchema: any;
export declare const insertChatSchema: any;
export declare const insertMessageSchema: any;
export declare const insertMediaSchema: any;
export declare const insertDocumentSchema: any;
export declare const schema: {
    users: any;
    chats: any;
    messages: any;
    media: any;
    documents: any;
    keywords: any;
    emergencyFlows: any;
    images: any;
    chatExports: any;
};
