// GENERATED by AI agent on 2025-09-27
// ESM version
import { pgTable, text, timestamp, jsonb, integer, boolean } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { z } from 'zod';

// ユーザーテーブル
export const users = pgTable('users', {
  id: text('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  username: text('username').notNull().unique(),
  password: text('password').notNull(),
  displayName: text('display_name').notNull(),
  role: text('role').notNull().default('employee'),
  department: text('department'),
  description: text('description'),
  created_at: timestamp('created_at').defaultNow().notNull(),
});

// チャットテーブル
export const chats = pgTable('chats', {
  id: text('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  userId: text('user_id').notNull(),
  title: text('title'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// メッセージテーブル
export const messages = pgTable('messages', {
  id: text('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  chatId: text('chat_id').notNull(),
  senderId: text('sender_id').notNull(),
  content: text('content').notNull(),
  isAiResponse: boolean('is_ai_response')
    .notNull()
    .default(false),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// 機種テーブル
export const machineTypes = pgTable('machine_types', {
  id: text('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  machineTypeName: text('machine_type_name').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// 機械テーブル
export const machines = pgTable('machines', {
  id: text('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  machineTypeId: text('machine_type_id')
    .notNull()
    .references(() => machineTypes.id),
  machineName: text('machine_name').notNull(),
  serialNumber: text('serial_number'),
  location: text('location'),
  status: text('status').notNull().default('active'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// 基本ドキュメントテーブル
export const baseDocuments = pgTable('base_documents', {
  id: text('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  title: text('title').notNull(),
  content: text('content').notNull(),
  category: text('category'),
  tags: jsonb('tags'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// 履歴アイテムテーブル
export const historyItems = pgTable('history_items', {
  id: text('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  machineId: text('machine_id')
    .notNull()
    .references(() => machines.id),
  title: text('title').notNull(),
  description: text('description'),
  status: text('status').notNull().default('open'),
  priority: text('priority').notNull().default('medium'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// 履歴画像テーブル
export const historyImages = pgTable('history_images', {
  id: text('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  historyItemId: text('history_item_id')
    .notNull()
    .references(() => historyItems.id),
  imagePath: text('image_path').notNull(),
  description: text('description'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// サポート履歴テーブル
export const supportHistory = pgTable('support_history', {
  id: text('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  machineId: text('machine_id')
    .notNull()
    .references(() => machines.id),
  issueDescription: text('issue_description').notNull(),
  solution: text('solution'),
  status: text('status').notNull().default('open'),
  priority: text('priority').notNull().default('medium'),
  assignedTo: text('assigned_to'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
  jsonData: jsonb('json_data').notNull(),
  imagePath: text('image_path'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// スキーマ検証用のZodスキーマ
export const insertChatSchema = z.object({
  id: z.string().optional(),
  title: z.string(),
  description: z.string().optional(),
  userId: z.string(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});

export const insertMessageSchema = z.object({
  id: z.string().optional(),
  chatId: z.string(),
  content: z.string(),
  role: z.enum(['user', 'assistant', 'system']),
  timestamp: z.date().optional(),
});

export const insertMediaSchema = z.object({
  id: z.string().optional(),
  messageId: z.string(),
  type: z.string(),
  url: z.string(),
  filename: z.string().optional(),
  size: z.number().optional(),
  createdAt: z.date().optional(),
});

// スキーマオブジェクト
export const schema = {
  users,
  chats,
  messages,
  machineTypes,
  machines,
  baseDocuments,
  historyItems,
  historyImages,
  supportHistory,
  insertChatSchema,
  insertMessageSchema,
  insertMediaSchema,
};