name: Azure Container Deploy

on:
  push:
    branches:
      - feature/ver2.10  # 実行対象ブランチを指定

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: emergencyassistanceregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t emergencyassistanceregistry.azurecr.io/emergency-assistance:latest .

      - name: Push Docker image
        run: |
          docker push emergencyassistanceregistry.azurecr.io/emergency-assistance:latest

      - name: Azure Web App Deploy (Container)
        uses: azure/webapps-deploy@v2
        with:
          app-name: emergency-assistance-app
          images: emergencyassistanceregistry.azurecr.io/emergency-assistance:latest
