name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - feature/2.10
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - feature/ver2.10

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Static Web App

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Build Vite project
        run: npm run build
        working-directory: ./client

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/client"
          output_location: "dist"

