# Azure App Service GitHub Actions Workflow
# バックエンド（Node.jsアプリ）をビルドし、Azure App Service にデプロイ
name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - buckup
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Prepare minimal server deployment for Function App
        run: |
          mkdir -p deploy-package
          # Copy essential server files
          cp server/index-minimal.ts deploy-package/index.ts
          # Create Function App compatible package.json
          cat > deploy-package/package.json << 'EOF'
          {
            "name": "emergency-backend-function",
            "version": "1.0.0",
            "type": "module",
            "main": "index.ts",
            "scripts": {
              "start": "tsx index.ts"
            },
            "dependencies": {
              "express": "^4.21.2",
              "cors": "^2.8.5",
              "tsx": "^4.20.3"
            }
          }
          EOF
          # Create host.json for Function App
          cat > deploy-package/host.json << 'EOF'
          {
            "version": "2.0",
            "functionTimeout": "00:05:00",
            "extensions": {
              "http": {
                "routePrefix": ""
              }
            }
          }
          EOF
          # Install dependencies
          cd deploy-package
          npm install --legacy-peer-deps
      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'emergency-backend-api'
          package: 'deploy-package'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
