# Azure App Service GitHub Actions Workflow
# バックエンド（Node.jsアプリ）をビルドし、Azure App Service にデプロイ
name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - buckup
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install root dependencies
        run: |
          npm ci --legacy-peer-deps || echo "Root install failed, continuing"
      - name: Install server dependencies
        run: |
          cd server
          npm ci --legacy-peer-deps || echo "Server install failed, continuing"
      - name: Install shared dependencies
        run: |
          cd shared
          npm ci --legacy-peer-deps || echo "Shared install failed, continuing"
      - name: Build shared
        run: |
          cd shared
          npm run build || echo "Shared build failed, continuing"
      - name: Build server
        run: |
          cd server
          npm run build || echo "Server build failed, continuing"
      - name: Copy necessary files for deployment
        run: |
          mkdir -p deploy-package
          cp -r server/* deploy-package/
          cp -r shared/dist deploy-package/shared/ || echo "No shared dist found"
          cp package.json deploy-package/
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'emergency-backend-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'deploy-package'
