# Azure App Service GitHub Actions Workflow
# バックエンド（Node.jsアプリ）をビルドし、Azure App Service にデプロイ
name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - buckup
      - deployment-fix
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Prepare full backend deployment
        run: |
          mkdir -p deploy-package
          
          # サーバーファイルをコピー
          cp -r server/ deploy-package/
          cp -r shared/ deploy-package/
          cp -r knowledge-base/ deploy-package/
          cp -r migrations/ deploy-package/
          
          # package.jsonをコピー
          cp package.json deploy-package/
          cp tsconfig.json deploy-package/
          cp drizzle.config.ts deploy-package/
          
          # 環境ファイルの設定（本番用）
          cat > deploy-package/.env << 'EOF'
          NODE_ENV=production
          PORT=3001
          LANG=ja_JP.UTF-8
          LC_ALL=ja_JP.UTF-8
          NODE_OPTIONS=--max-old-space-size=4096
          SESSION_SECRET=emergency-assistance-session-secret-production
          EOF
          
          # 依存関係のインストールとビルド
          cd deploy-package
          npm install
          npm run build
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'emergency-backend-webapp'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'deploy-package'
