# Azure App Service GitHub Actions Workflow
# バックエンド（Node.jsアプリ）をビルドし、Azure App Service にデプロイ
name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - buckup
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install root dependencies
        run: |
          npm ci --legacy-peer-deps
      - name: Install root dependencies only
        run: |
          npm ci --legacy-peer-deps
      - name: Prepare minimal server deployment (no builds)
        run: |
          mkdir -p deploy-package
          # Copy only essential server files for minimal server
          cp server/index-minimal.ts deploy-package/
          cp server/package.json deploy-package/
          # Install production dependencies in deploy package
          cd deploy-package
          npm install --production --legacy-peer-deps
          # Create a simple startup script for Azure
          cat > server.js << 'EOF'
          const { spawn } = require('child_process');
          
          // Install tsx if not available and start the server
          const server = spawn('npx', ['tsx', 'index-minimal.ts'], {
            cwd: __dirname,
            stdio: 'inherit',
            env: { ...process.env, NODE_ENV: 'production' }
          });
          
          server.on('error', (err) => {
            console.error('Server startup error:', err);
            process.exit(1);
          });
          
          server.on('exit', (code) => {
            console.log('Server exited with code:', code);
            process.exit(code);
          });
          EOF
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'emergency-backend-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'deploy-package'
