name: Build Only (Cloud Agnostic)

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: "18.x"

jobs:
  # ===========================================
  # ビルドのみ（クラウド依存なし）
  # ===========================================
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: ["16.x", "18.x", "20.x"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install root dependencies
        run: npm ci

      - name: Install workspace dependencies
        run: npm run install:all

      - name: Lint code
        run: npm run lint
        continue-on-error: true

      - name: Build shared package
        run: |
          cd shared
          npm run build

      - name: Build server
        run: |
          cd server
          npm run build

      - name: Build client
        run: |
          cd client
          npm run build
        env:
          VITE_API_BASE_URL: http://localhost:3001
          NODE_ENV: production

      - name: Run tests
        run: npm run test
        continue-on-error: true

      # アーティファクトの保存（主要OSのみ）
      - name: Upload build artifacts
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            client/dist/
            server/dist/
            shared/dist/
          retention-days: 7
