name: Deploy Frontend (SWA)

on:
     workflow_dispatch:
  push:
    branches: [ backup-clean ]
    paths:
      - "client/**"
      - ".github/workflows/deploy-frontend-swa.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20
      VITE_API_BASE_URL: https://Emergencyassistance-sv.azurewebsites.net
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: |
            client/package-lock.json

      - name: Install deps (client)
        working-directory: client
        run: npm ci

      - name: Build (client)
        working-directory: client
        env:
          VITE_API_BASE_URL: ${{ env.VITE_API_BASE_URL }}
        run: npm run build

      - name: Add routes.json (SPA fallback)
        working-directory: client
        run: |
          mkdir -p dist
          cat > dist/routes.json <<'JSON'
          {
            "routes": [
              { "route": "/**", "serve": "/index.html", "statusCode": 200 }
            ]
          }
          JSON

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "client"
          output_location: "dist"
